### ISSUE TITLE
why is the friends module butt-dialing my friends?

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-friends#26]
My expectation is that this is the module which tells me who my friends are and what the distance is to different people.

I was very surprised to find this was also managing some replication. It's like my address book on my phone is polling people without me asking it to. I think it was @mmckegg that pointed out this surprising behaviour.

Can we find a different home for it please?

**Comment by dominictarr** [comment]
it's just these 4 lines: https://github.com/ssbc/ssb-friends/blob/master/index.js#L95-L103

okay so we can move it but where to put it? ssb-default-opinions ?
there is not just this opinion... there are also a couple of other things like this that are similar, such as which addresses to add to the peers table, those opinions are also scattered around a bit.

**Comment by staltz** [comment]
> it's just these 4 lines: https://github.com/ssbc/ssb-friends/blob/master/index.js#L95-L103

That looks to me look it could be `ssb.replicate.requestAll()` or `.start()`, but it's replication logic, in particular, it's replication scheduling. And as an API `.requestAll()` it wouldn't necessarily be called on startup, but the client app can control when should it start.

**Comment by dominictarr** [comment]
@staltz I moved this out of replication because I realized a plugin should focus on _how_ it does what it does, not _what/who_ it does it to. replication should focus on the hard part: how to reliably replicate all the feeds that are desired - this is a question that has a right answer (facts, algorithms). On the other hand, who to replicate is a fluffy thing there is no real right or wrong, it's easy to imagine other reasons you want to replicate different feeds (opinions). I want facts and opinions clearly separated so that people can easily maintain their own opinions.

**Comment by dominictarr** [comment]
@mixmix is quite right in suggesting that actually the `ssb-friends` module is also highly technical, about facts. that means that the opinions of who to replicate should be neither in replicate or friends.

**Comment by staltz** [comment]
Correct, I see now that 

```js
//pull(
    layered.hopStream({live: true, old: true}),
//  pull.drain(function (data) {
//    if(data.sync) return
//    for(var k in data) {
//      sbot.replicate.request(k, data[k] >= 0)
//    }
//  })
//)
```

means "who to replicate", and

```
//pull(
//  layered.hopStream({live: true, old: true}),
    pull.drain(function (data) {
      if(data.sync) return
      for(var k in data) {
        sbot.replicate.request(k, data[k] >= 0)
      }
    })
//)
```

means "replicate all these", and indeed it's a cross cutting concern. It seems small enough code that it could be put in application logic though.

**Comment by dominictarr** [comment]
there are a couple of other instances like this throughout the system:

* add local peers to gossip: https://github.com/ssbc/ssb-server/blob/master/plugins/local.js#L52-L63
* `ssb-replicate` also has policy to always replicate local peers: https://github.com/ssbc/ssb-replicate/blob/master/legacy.js#L194-L200 it would be better if that was handled by local plugin, so that this happened when replicating on ebt also. The reason it's like this is because legacy replication predates this policy of separating how from what.
* add pub messages to gossip: https://github.com/ssbc/ssb-gossip/blob/master/init.js#L15-L27
* add `address` messages to gossip: https://github.com/ssbc/ssb-device-address/blob/master/index.js#L35-L64 (this should supercede `pub` messages)

That's everything, I'm 89% sure.

If this pattern was clarified I think it should cover both replication and peers.

**Comment by dominictarr** [comment]
After this and https://github.com/ssbc/ssb-server/issues/629 I'm thinking:

* implementing a `ssb-default-opinions` module
* switching to events to coordinate between plugins `emit("replicate:request", id, true)` instead of `replicate.request(id, true)` then ssb-ebt won't depend on `ssb-replicate`.
* adding `"replicate:block"` event, to remove the [just-get-it-working where ebt depends on ssb-friends](https://github.com/ssbc/ssb-ebt/blob/master/index.js#L139-L167) SLAGIATT
* ditching hoox module (too flexible / non-obvious) for purpose specific adapters, such as [`addMap`](https://github.com/ssbc/ssb-db#ssbdbaddmap-fn)
 
does anyone else have a concrete suggestion?

**Comment by dominictarr** [comment]
@staltz @mixmix @ahdinosaur @christianbundy

**Comment by staltz** [comment]
> * implementing a `ssb-default-opinions` module

I think we should find a more constrained "opinions" container, because I fear such module would slowly become a centralization point for all sorts of random assorted logic. Instead, we could create a few limited-in-scope-and-purpose packages, like `ssb-default-replication`, `ssb-default-gossip`, etc, so that it's clear you *shouldn't put anything* in those packages.

> * switching to events to coordinate between plugins `emit("replicate:request", id, true)` instead of  `replicate.request(id, true)` then ssb-ebt won't depend on `ssb-replicate`.

Yes I agree this is an improvement.

> * adding `"replicate:block"` event, to remove the [just-get-it-working where ebt depends on ssb-friends](https://github.com/ssbc/ssb-ebt/blob/master/index.js#L139-L167)

:+1: 

> * ditching hoox module (too flexible / non-obvious) for purpose specific adapters, such as [`addMap`](https://github.com/ssbc/ssb-db#ssbdbaddmap-fn)

:+1:

> * event style interaction would also apply to gossip peers. `emit("peers:add", peer_address)`? @staltz 

Yes I could do this, but see my next comment...

> does anyone else have a concrete suggestion?

A global event emitter like `emit('whatever-string')` is an easy-to-write approach, but hard to debug, because once an event is emitted, it becomes difficult to know who is consuming it. Instead, since we anyway would have scopes for these strings (by scope I mean `emit('SCOPE:event')`), we could just have these ssb plugins export event streams (either pull stream or something else), then we would have a more consistent approach in the ecosystem since we're already using these pull streams everywhere. We could either have multiple introspection streams per package, or one thick introspection stream that emits all interesting events for that module, for instance:

```js
pull(
  sbot.replicate.introspection(),
  pull.drain(console.log) // 'request', 'block'
)
```

Of course the name `introspection` can be bikeshed

**Comment by dominictarr** [comment]
@staltz I don't quite follow, prehaps I misunderstood you, or you misunderstood me or both.

Clarifying what I meant:

currently ssb-friends calls `replicate.request(id, true)` this would be replaced by ssb-friends (or `ssb-?-opinions` emitting `emit("replicate:request", id, true)`. We could give the replicate plugin a method that is called by others to send it an event - oops! that is what we already have. That isn't working because there are two plugins `replicate` and `ebt` that are performing replication.

Calling `<plugin>.introspection` to receive a stream of events produced by `<plugin>` is fine, but I'm actually suggesting the opposite - the events (in this case) are for the `<plugin>` it _receive messages_.

finding where the consumers are - grep is your friend here! especially since the string will be "<scope>:<event>" that's really easy to grep for. `grep -R` for recursive, into node_modules. Could also have keep stack traces from `emitter.on(...)` and some method to call to get those, but I think grep is okay.
Also, in this case, it will be a handful of plugins listening to each other, and not registering and unregistering listeners, nor many parallel instances of each emitter, just one ssb-server mostly.

I do like the idea of some sort of more constained message bus, where for example, it was clear which modules where emitting and receiving each message (which I wouldn't say is the case with event-emitters)

**Comment by staltz** [comment]
> I'm actually suggesting the opposite - the events (in this case) are for the `<plugin>` it _receive messages_.

Oh, now I see what you mean. The emission of a string would be essentially a function call, but without explicitly importing the function. But do we need the strings to achieve this? For instance, why can't we still do `replicate.request(id, true)`, we could rewrite `ssb-ebt` so that its manifest `name` is `replicate`.

**Comment by dominictarr** [comment]
@staltz yes we could do that, but `ssb-replicate` (legacy replication) is _also_ named `replicate` so they'd need to _share_ the name in some way. The most obvious way, to me, is that there is some sort of _fallthough_ method, kinda like express's `next` - pass this on to the next handler. a method is called, the "top" plugin in that slot handles it, then (maybe) passes control to the next.

To evaluate an idea like that, I'd consider wether this pattern would be useful in other cases. Right now the other candidate for multiple implementations is gossip, but I don't think anyone is talking about running two gossip modules at once.

it would be significant change to of `secret-stack`, and I'm not sure wether anything else would use it.
emitting events would be easy though.

alternate, I just thought of now:
  * stub `replicate` plugin, that doesn't do anything, just defines the interface.
  * `ssb-replicate-legacy` extends that, via hooks.
  * `ssb-ebt` extends that, via hooks.

**Comment by staltz** [comment]
@dominictarr I'm guess I'm wondering why both `ssb-replicate` and `ssb-ebt` need to be installed simultaneously. And if they necessarily need to be both installed, why couldn't `ssb-ebt` *include/wrap* `ssb-replicate`. Like you, I wouldn't like to have a fallthrough mechanism implemented in secret-stack.

**Comment by christianbundy** [comment]
Just to chime in because I was mentioned above: I have no strong opinions, but I *am* reminded of the [depject readme](https://github.com/depject/depject#philosophy) and wonder whether we already have solutions to this sort of problem.

On the other hand, I wonder whether this parallels the discussion(s) on out-of-process plugins, and whether we should aim to solve these individually or whether The Right Solution is to nail them all together at the same time. For example: depject that exposes out-of-process plugins over muxrpc (?).

I understand that this comment vastly widens the scope of the discussion, so feel free to ignore if this is unhelpful or just too much to consider right now.

**Comment by mixmix** [comment]
I like the idea of `ssb-ebt` sitting in the replicate namespace, and totally deprecating `ssb-replicate`. It seems like that was the long term plan, and what I've been at the moment is that there are a huge number of pubs just not running ebt. I'd prefer to not wrap, because layers and layers get harder to maintain and grok.

depject is dangerous. I think it gets real scary as it stacks up and gets really hard to debug. Personally I don't think recurssive grep is something we should be expecting people to be doing to debug - with depject in particular recurssive grep just doesn't work if people nest their gives in the wrong way. (as in don't nest as flat strings using `depnest`)

I love @staltz ' idea about micro modular opinions in the `ssb-default-replication` pattern.

Then we can bundle them all in some module like `ssb-fat-controller` 

![image](https://user-images.githubusercontent.com/2665886/52592313-f4546380-2eaa-11e9-9325-f7164d4e2b2f.png)

**Comment by mixmix** [comment]
I am unreasonably happy with being able to weave that in. _send help, my dad brain is killing me slowly_

**Comment by dominictarr** [comment]
@mixmix https://www.youtube.com/watch?v=0jB5x-h_yYc

**Comment by dominictarr** [comment]
@staltz oh, I hadn't thought of `ssb-ebt` wrapping `ssb-replicate`. that's a great idea!

We do need to keep `ssb-replicate` though, because it's not the javascript implementation, it's much easier to roll a `ssb-replicate` implementation than `ssb-ebt` (i have some ideas there, but talk later) so removing legacy replication fully would not be helpful to the go team.

Yeah, depject didn't work out as intended. It was way too promiscious.
It mainly ended up being a require replacement (and require didn't need replacing).
Really, to work well, each modular interaction point needs to be carefully thought out, and explicit.

**Comment by christianbundy** [comment]
Yep, I think this is still relevant: https://github.com/ssbc/ssb-friends/blob/a6526fdeb55257e02c692b73572dc15773c3f9e8/index.js#L57-L66

I'd imagine that the next step here would be to move the butt-dialing code to ssb-gossip, which calls the stream from ssb-friends if available? I'm not sure.
