### ISSUE TITLE
How can we tell the difference between public and private follows/blocks?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-friends#43]

**Comment by Powersource** [comment]
So the clients that I'm aware of that have these features are patchwork (private blocks and follows), and manyverse (private blocks). I'm not keen on figuring out how patchwork does this, so could we maybe refactor this out of manyverse (and into ssb-friends) @staltz ?

**Comment by staltz** [comment]
I think that any encrypted message (including follows) once decrypted will have .metadata.private attached to msg.value.content or something like that

**Comment by staltz** [comment]
@arj03 I realized that this issue is a pretty big deal. Currently ssb-friends is blind to private blocks, and if other modules rely on `isBlocking`, then private blocks will slip through and the blocked authors appear in the UI, etc.

I also realize that this would require a reindexing in ssb-db2 (and flume as well, it seems), because the messages in the log would have to be decrypted.
